const errorResponse = require("../utils/errorResponse");

const signUp = (req, res, next) => {
  try {
  } catch (error) {
    errorResponse(error, res, req);
  }
};
